### ISSUE TITLE
Remove "Success" page and create success notification on Dashboard page

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#101]
Work together with @EkremGursoy to design the notification (he has the Error notification task)!

## Tasks
- Remove the "Sign Up Message desktop - Success" desktop page and "Success message" on mobile
- Duplicate the Dashboard page next to it
- Create an alert/notification for a Successful signup message with example text "Account created! Please check your email for instructions on how to verify your account."
- Repeat process for mobile version

## Design
- Success: Green background (#E8F5E9), green text (#388E3C), with a check icon.
- Create a notification box in the top right corner under the navigation bar (or wherever looks good)
- Follow style guide for alerts

- [x] Desktop version
- [x] Mobile version

**Comment by Mayamariaruth** [comment]
Parent ticket #86

**Comment by pauiws** [comment]
I have talked to Maya, and we agreed that we change notification design to this: 
- The success message can be changed to the primary color green 
![Image](https://github.com/user-attachments/assets/2fe6d47f-0753-4627-bd41-43468c3fba6c)

**Comment by Mayamariaruth** [comment]
@pauiws We will leave the design like this after discussing with the clients, no need to change it @QueenWoofie unless you have some new ideas to update the design with. The reference image I sent was a sleek look that we could maybe try out?

**Comment by QueenWoofie** [comment]
@Mayamariaruth Aside from making it flatter, wider and changing the position to look like the image @pauiws shared here I don't have any other ideas, so if the clients are good with the design as is I'll keep it so, I thought it looked good.

**Comment by Mayamariaruth** [comment]
Yes, we will keep it like below image instead but maybe we can make it more professional? @QueenWoofie 

![Image](https://github.com/user-attachments/assets/bbef069b-a61d-43b7-846d-f1d5b9cb98f0)

**Comment by QueenWoofie** [comment]
@Mayamariaruth I would say it look pretty sleek and follows the style guide nicely with the way it looks now. I'm afraid if we overdo it it will just end up looking poorly made.

**Comment by pauiws** [comment]
Desktop version is good but the mobile version doesnt have the same size as the failed notification.

**Comment by pauiws** [comment]
Review completed.
