### ISSUE TITLE
Contact form error validation

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#102]
As a user, I want the contact form to display clear error messages,
so that I can easily understand and correct any mistakes when submitting my information.

# Acceptance criteria
- Display a concise error message below the invalid field when a user submits the form with incomplete or invalid fields
- Text example (e.g., "Please enter a valid email address")
- Highlight error messages with a distinct red color

## Tasks
- Create duplicate page of Contact Form page on desktop and mobile
- Edit design to include error messages under each form field to display form field error validation
- Error messages in accent color (#FF5722) below the field.
- Create component of error form field

**Comment by Martinekong** [comment]
I have made a component for error form field, created a duplicate contact page, and added the component and error message both on mobile and desktop.

**Comment by Mayamariaruth** [comment]
@pauiws I added a comment to this on the Figma page !

**Comment by Martinekong** [comment]
Aligned the error messages in the contact forms on desktop and mobile to the left so it matches the form labels.

**Comment by pauiws** [comment]
@Martinekong Im unsure of the design, still reviewing and will possibly come up with a better design 
@Mayamariaruth sending you a message on this :)

**Comment by pauiws** [comment]
I have talked to Maya, and we agreed that we change notification design to this: 
- The success message can be changed to the primary color green 
![Image](https://github.com/user-attachments/assets/2fe6d47f-0753-4627-bd41-43468c3fba6c)

**Comment by pauiws** [comment]
Review completed
