### ISSUE TITLE
Add hover/click states to tables

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#105]
## Tasks
- Add hover/click states to all tables

**Comment by Mayamariaruth** [comment]
Parent ticket #59

**Comment by Jereriviel** [comment]
I have added hover/cliked states to the Select Student table and the Select User table.

Tables left:
- Student Results
- Manage User

**Comment by Jereriviel** [comment]
I am done adding hover/clicked states to all tables in Desktop.

**Comment by pauiws** [comment]
Looks good! Review Completed
