### ISSUE TITLE
Style search bars

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#107]
## Tasks
- Style the search bars on Results Students page, Results Table page, Manage User search and Manage User

<br>

- [ ] Mobile
- [ ] Desktop

## Design
- Match them to the form fields but experiment if you want!
Input Fields:
Border: 1px solid light gray (#CCCCCC)
Focus: Border changes to primary color (#4CAF50)
Padding: 8px

**Comment by Martinekong** [comment]
I have redesigned the search field, made two components - search field and search btn, and prototyped it so it has a focus state and a hover on btn state. Added the components to the style guide. Added the search field to the relevant pages on both desktop and mobile.

**Comment by pauiws** [comment]
Looks good, review completed
