### ISSUE TITLE
Modals

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#108]
As a student/admin/teacher, I want modals for confirmations and cancellations to clearly communicate actions, so that I can make informed decisions before proceeding or canceling tasks.

## Acceptance Criteria 
- Modals are displayed prominently and center-aligned on the screen.
- The modal includes a clear title, concise message, and action buttons (e.g., Confirm, Cancel).
- Clicking "Confirm" executes the action, while "Cancel" closes the modal without changes.
- The modal is dismissible using the "Cancel" button or an "X" icon.
- The background is dimmed and non-interactive when the modal is open.

<br>

- [x] #109 
- [x] #110 
- [x] #111

**Comment by Jereriviel** [comment]
All three tasks completed and in review.

**Comment by pauiws** [comment]
Review completed.
