### ISSUE TITLE
Create modal overlay for deleting student results

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#110]
## Tasks
- Create modal overlay with style guide design for when user clicks delete button to delete student results on Manage User page and Results Table
- Include a secondary Cancel button and a primary Confirm button saying "Yes, Delete Results"
- Title heading could be "Delete Student Results?"
- Body text could be "Are you sure you want to delete this student's results? This action is permanent and cannot be undone."
- Add prototype interactions for delete buttons (display overlay), cancel buttons (close overlay) and confirm buttons (close overlay)

<br>

- [x] Mobile (make sure Carina is done with the table stylings to be able to connect the overlay to the delete button)
- [x] Desktop

## Design
- Structure: Centered on the screen with a semi-transparent background overlay.
- Size: 400-600px wide, depending on content.
- Actions: Include primary and secondary buttons for confirmations and cancellations.
- Follow style guide for headings and body texts

**Comment by Mayamariaruth** [comment]
Parent ticket #108

**Comment by Jereriviel** [comment]
Completed.

**Comment by pauiws** [comment]
Review completed.
