### ISSUE TITLE
Create modal overlay for user deleting their profile

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#111]
## Tasks
- Create modal overlay with style guide design for when user clicks delete button to delete their profile on Profile page
- Include a secondary Cancel button and a primary Confirm button saying "Yes, Delete Profile"
- Title heading could be "Delete Your Profile?"
- Body text could be "Are you sure you want to delete your profile? This action is permanent and cannot be undone."
- Add prototype interactions for delete buttons (display overlay), cancel buttons (close overlay) and confirm button (user is taken back to home)

<br>

- [x] Mobile
- [x] Desktop

## Design
- Structure: Centered on the screen with a semi-transparent background overlay.
- Size: 400-600px wide, depending on content.
- Actions: Include primary and secondary buttons for confirmations and cancellations.
- Follow style guide for headings and body texts

**Comment by Mayamariaruth** [comment]
Parent ticket #108

**Comment by Jereriviel** [comment]
Completed.

**Comment by pauiws** [comment]
Review completed.
