### ISSUE TITLE
Add auto-layout to all pages

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#112]
## Tasks
- Create an auto-layout with the grids and style guide 
- Apply to all pages

<br>

- [x] Desktop @Jereriviel 
- [x] Mobile @QueenWoofie

**Comment by Jereriviel** [comment]
I created a components for the circle illustration to be able to display it properly in the dekstop and mobile layouts. Replaced all previous illstrations with these.

**Comment by Jereriviel** [comment]
I applied new (auto) layout to the dashboard options on all three dashboard pages on desktop, as there were differences in spacing, font style and sizes across the three pages.

**Comment by Jereriviel** [comment]
Adding auto layout for desktop pages completed.

What I have done is:

- Created a Container for all content in the page. This container is 1280px wide and has a vertical spacing of 48px, except for the pages where the content is smaller than the presentation height of 1080px, on these pages the spacing is on auto, keeping the content centered.
- I have grouped some content to fit within the auto layout and have tried to make sure it follows the spacing guidelines and having consistency across all pages.
- I have made some minor adjustments to font sizing where I have seen inconsistencies.

Just for keeping a record, the pages I have added auto layout are:

- Landing Page Desktop
- Log in Desktop 
- Log in Success Alert
- Sign Up Desktop Failed
- Sign Up Desktop
- Registration
- Dashboard Admin Desktop 
- Dashboard Teacher Desktop
- Dashboard Student Desktop
- Results Student Desktop
- Profile Card Desktop
- Profile Action Desktop
- Settings Desktop
- -Add Students Desktop
- Add Teachers
- Add Results
- Manage User Search
- Manage User
- About
- Contact
- Contact - On Error

**Comment by pauiws** [comment]
Review completed.
