### ISSUE TITLE
Add a "Add school" page for admin user

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#120]
## Tasks
- Copy paste the "Add student" page and name it "Add school" and position it next to the other similar pages
- Update all the texts to match an admin user adding a new school to the system:
For example "To add students, upload an Excel spreadsheet with this format:" should be changed to "To add schools, upload an Excel spreadsheet with this format:"

- [x] Desktop
- [x] Mobile

**Comment by pauiws** [comment]
Review Completed.
