### ISSUE TITLE
Add a "Top-performing students" page for teachers

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#121]
## Tasks
- Copy paste the "Select user search" page or "Student results" page
- Update the texts to match a page displaying the top performing students to a teacher
- Remove action buttons (edit, delete, add etc)
- Keep the search bar!

<br>

- [x] Desktop
- [x] Mobile

**Comment by Jereriviel** [comment]
Page added to desktop.

**Comment by Jereriviel** [comment]
Page added to mobile, moving to review.

**Comment by pauiws** [comment]
Review Completed.
