### ISSUE TITLE
Add hero image to landing page

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#139]
## Tasks
- Add chosen hero image to landing page
- Update h1, body text and buttons to fit on top of the image

<br>

- [x] Desktop
- [x] Mobile

**Comment by AilinMari** [comment]
Trying different things with this one. Was thinking of makin a video hero "image" of the product being in use, or just have a picture that indicates what it is made for. Still working on the idea, and trying different things

**Comment by Samal-Ibrahim** [comment]
the hero image is very nice on the landing page, but the resalotion is kinda low?

**Comment by AilinMari** [comment]
I made the image with help from AI, so it probably looks like that because there is not real humans on the picture?

**Comment by Mayamariaruth** [comment]
Could we make the hero image sit right below the navbar on mobile and make it bigger as well so it looks more like a hero section? We could potentially also remove the Circles illustration so there's only focus on the hero image on the landing page, what do you think? @AilinMari

**Comment by AilinMari** [comment]
I agree :) The image was just following the auto layout. That’s why it is placed there

Sendt fra Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Samal-Ibrahim** [comment]
@Mayamariaruth i agree, but then it could look very empty, i suggest making it smaller rather than fully remove it, or replace it with something else?
