### ISSUE TITLE
Add hover effect to user image instead of pencil icon to edit

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#143]
## Tasks 
- Add hover effect with a picture icon and text saying "Change picture" to user image on Profile pages
![Image](https://github.com/user-attachments/assets/eed44e05-cb04-416b-818e-442dfa846f9f)

- [x] Desktop
- [x] Mobile

**Comment by kristinatonnessen** [comment]
A hover effect won't show up when using the site on a phone, are we still going to add it? 🤔 @Mayamariaruth

**Comment by Mayamariaruth** [comment]
Yes, you're right! Maybe just add the picture icon next to it or you guys decide what you think looks best!
![Image](https://github.com/user-attachments/assets/31e6fa8e-e4b5-4764-89ce-7058dfa36d2b)

**Comment by barumski** [comment]
Both ready for review.

**Comment by Janicke92** [comment]
I can only find the picture icon in the mobile version, and not desktop.

**Comment by barumski** [comment]
> I can only find the picture icon in the mobile version, and not desktop.

That is because it is under the hover effect on the desktop version. The default is the letters, and when you hover over it in the presentation mode you will see it. 

I can do some changes to it if wanted, let me know.

**Comment by Janicke92** [comment]
I see it now! Great :)
