### ISSUE TITLE
Add border to contact forms

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#146]
## Tasks
- Add a border (like on the profile pages forms or if you have a better design!) around the forms to fill up some more white space and make design cohesive.

<br>

- [x] Desktop
- [ ] Mobile

**Comment by KatRan2104** [comment]
I have added borders, and cleaned up the spaces so that they go with the style guide. Take a look and I can make the last few tomorrow.

**Comment by KatRan2104** [comment]
I just realised I have done the wrong thin... I've edited all the forms....

**Comment by KatRan2104** [comment]
Did it now.

**Comment by Mayamariaruth** [comment]
What happened to the contact form? There are two borders now, one border around just the form fields and a border around the whole form. Wouldn't it make more sense to have one border around the whole content including the heading and body text? like the other forms on other pages @KatRan2104 

![Image](https://github.com/user-attachments/assets/a3e3c863-05eb-4e53-9ae3-c1b9faa50731)

**Comment by KatRan2104** [comment]
good question, not what I intended to do. Just the outside border. Might have something to do with it being a table? I´ll try to fix it now :)

**Comment by KatRan2104** [comment]
fixed it now hopefully!

**Comment by Mayamariaruth** [comment]
@KatRan2104 Shouldn't the heading and body text be inside the border too? So it matches the rest of the pages with forms+border
