### ISSUE TITLE
Change DOB form fields to editable form fields on Edit Profile page

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#147]
## Tasks 
- Change the DOB form fields to the normal form field component (without the gray color) to make them look editable
- Move the DOB form field to below the Email field so all editable fields are together (on the admin and teacher pages)

- [x] Desktop
- [x] Mobile

**Comment by Anne-Zwift** [comment]
- Changed the DOB form fields to the normal form field component.
- Profile card desktop admin. : Deleted a rectangle with the eye closed. Before adjusting the fields on the Profile card desktop admin. Rearanging the naming of T boxes.
- Profile card desktop teacher: Sending Rectangle 94 to the back before adjusting the field. Creating new T boxes for the lines that were missing (email, Id, DOB), naming and grouping them.


@Mayamariaruth @kristinatonnessen @Janicke92  moving this to review.

**Comment by Janicke92** [comment]
Wonderful! :)
