### ISSUE TITLE
Make mobile hamburger menu full screen

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#148]
## Tasks
- Update the hamburger dropdown menu to be full screen (the whole mobile screen so you can't see the content underneath)
- For the not logged in user, add the Login page and Signup page to the navbar options
- If it looks a bit empty then maybe add some icons to fill up more space (the matching icons on the sidebar and dashboard)
- Maybe make the texts bigger

**Comment by Martinekong** [comment]
I have updated the hamburger menu to now take up the full screen. I made new components, and added them to the style guide. 
I added "login" and "signup" to the not logged in user, and prototyped and added it to all mobile pages. I had to make the menu as long as the longest page to make it fill all heights.

**Comment by Martinekong** [comment]
I also added the icons I used for: "login", "signup", "contact" and "about" to the style guide. Let me know if there is anything.

**Comment by pauiws** [comment]
Looks good, review completed.
