### ISSUE TITLE
Update excel screenshots to a table design

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#149]
## Tasks
- Update the excel screenshots on the "Add student, teacher" etc pages to real tables that look like an excel spreadsheet
- Its still only meant to show how the user can add new users with an excel spreadsheet but it doesn't look good with the excel sheet being an image right now

<br>

- [x] Desktop 
- [x] Mobile

**Comment by Jereriviel** [comment]
Excel table screenshots have been replaced with Excel table components on both mobile and desktop. Main components are found in the Style Guide.

**Comment by pauiws** [comment]
Review completed.
