### ISSUE TITLE
Make "Student results" table rows editable

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#150]
## Tasks
- Update the rows on the Student results page so the teacher can edit the results right in the row or make an edit popup?

- [x] Desktop
- [x] Mobile

**Comment by Jereriviel** [comment]
@Mayamariaruth These are already editable in both desktop and mobile. Not sure what you mean?

**Comment by Mayamariaruth** [comment]
So we have the “Edit” button right? I’m thinking that we add a popup (like the other table popups on mobile for example) when it’s clicked and show that the teacher can edit the results. So you add a form field in the popup to display that the results can be changed. Does that make sense? @Jereriviel

**Comment by Jereriviel** [comment]
Oh, ok, got it! :)

**Comment by Jereriviel** [comment]
Task complete.

In desktop view each row gets an row overlay when clicking "Edit", where you can edit the grade.

In mobile view the edit button on the information popup changes the overlay with a new one where you can edit the grade.

**Comment by pauiws** [comment]
Review completed.
