### ISSUE TITLE
Add all navbar components to styleguide

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#153]
## Tasks
- Add all the updated navbar components to the styleguide 
- Make sure they're ready! Silver birch and Willow Glade are updating the mobile navbars

**Comment by KatRan2104** [comment]
There were so many options, so I added the once that covered the most of them, and the rest are updated in the more detailed styleguide I think?

**Comment by Janicke92** [comment]
Great! :)
