### ISSUE TITLE
Prototype - add hover/active states

### ISSUE THREAD

**Issue by sulenchy** [NoroffFEU/edu-gate#59]
## Tasks
- Create a list of what elements need hover/click states (e.g. all buttons need hover/click states with different colors etc)

- [x] #105 
- [x] #114
- [x] #100

**Comment by sulenchy** [comment]
Here is the parent ticket https://github.com/NoroffFEU/edu-gate/issues/50

**Comment by Jereriviel** [comment]
Add hovered/clicked state to tables completed.
