### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#62]
As a user/teacher/admin, I want to have breadcrumbs in the interface,
so that I can navigate between pages more easily and track where I am within the application.

## Acceptance Criteria
- Breadcrumbs dynamically display the current page hierarchy and updates appropriately as the user navigates.
- Component follows the style guide for size, font, colors, and spacing.
- Added to all multi-level navigational pages.

## Tasks
- Add on every page except the Landing page as "Home / Results / Add Results" or "Home > Results > Add Results"
- Remove the blue clock icon on the mobile version (just below the navigation bar)
- Text color: Medium Gray (#757575) with primary color on the current page
- Font: Roboto
- Size: 16px
- Position: Below navigation bar on the left side
- The breadcrumbs should be added to the style guide under "Links/Breadcrumbs"

- [x] mobile 
- [x] computer

**Comment by Martinekong** [comment]
- Added breadcrumbs to all multi-level pages, with font Roboto, a font-size of 16px, gap of 24px for desktop and 16px for mobile, in the color medium gray (#f5f5f5). 
- Changed H1s on "results" and "change user" to match the navigation. 
- Added the breadcrumbs to the style-guide under typography. 
- Removed the blue clock icon on mobile.

**Comment by BtheBEST84** [comment]
@Martinekong It is lookin pretty good! I think the color on the active page is supposed to be the primary color though. It should be this one? #4CAF50. Can you have a look at that?

**Comment by Martinekong** [comment]
Sure! I will check it out now!

**Comment by Martinekong** [comment]
I changed active page to to font-weight medium and primary color + updated the breadcrumbs in the style guide

**Comment by BtheBEST84** [comment]
Thank you :-) Amazing! The figma file is starting to look really good now!

**Comment by BtheBEST84** [comment]
Review complete! :-)
