### ISSUE TITLE
Pagination and table styling

### ISSUE THREAD

**Issue by BtheBEST84** [NoroffFEU/edu-gate#63]
As a user/teacher, I want to view and interact with tables that follow a consistent style and include pagination, so that I can easily navigate large data sets and access the information I need.
 
## Acceptance critera
- Definition of "data set gets too big" is defined
- Pagination is displayed below the table and allows users to navigate between pages.
- Tables across all pages are consistent in structure and functionality.
- Alternate row colors and hover effects improve readability and interactivity (implementation details to follow style guide).

### Tables
- Update table stylings to match on every page and follow style guide:
Headers: Use primary color text and bold font for clarity.
Rows: Alternate light gray background (#F9F9F9) to improve readability.
Hover Effect: Slight background change on row hover to indicate interactivity.
- Add delete buttons for every table row so admin can delete results (on Results page and Change User page on result tables):
Alert Button (for delete actions):
Background: Accent color (#FF5722)
Text: White
Hover: Darker shade of accent color (#E64A19)

### Pagination
- Add pagination to table views on Results and Change user pages.
- Remove the scroll bars
- Pagination controls should include page numbers and Next, Previous, First, and Last buttons.
Style: Primary color for active pages, gray for inactive.
Font: Roboto
Size: Follow style guide.
Position: Below the table, centered horizontally.
- Add to the style guide under "Navigation."

- [x] mobile 
- [x] computer

**Comment by Jereriviel** [comment]
I am making components for the tables while styling and adding pagination to them.

**Comment by Jereriviel** [comment]
Created components for Desktop Select Student and Desktop Student Results today, including both styling and pagination. Will continue with the rest of the desktop components (and hopefully mobile as well) tomorrow.

Remaining tables are:
- Add students
-  Add teachers
- Add results
- Select user
- Manage user

**Comment by Jereriviel** [comment]
Dekstop tables are done and implemented. The Add student, Add teachers and Add results tables were only screenshots of examples for the user to follow, so I just made them bigger to fit the grid. I have not considered the layout carefully when placing the tables, as I understand that another team will taking care of this for all pages.

**Comment by Mayamariaruth** [comment]
Parent ticket #88

**Comment by Jereriviel** [comment]
I have now finished and implemented all mobile tables. I did some minor prototyping just to so the tables can be scrolled horizontally when in presentation view.

**Comment by pauiws** [comment]
I think it looks good and partially the same with both mobile and desktop version. Review complete

**Comment by Jereriviel** [comment]
Working on redoing the mobile tables now, removing the scroll, making the tables smaller with less information and adding an overlay with more information.

**Comment by Jereriviel** [comment]
Closing this task again as the changes has its own task: https://github.com/NoroffFEU/edu-gate/issues/131
