### ISSUE TITLE
Add descriptive icon labels

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#70]
## Tasks
- Add descriptive text under the icons on the Dashboard mobile page, same as desktop pages
- Add descriptive text under the icons on the Settings mobile page, same as desktop pages
- Align the Settings icons vertically 

## Note!
- The "Change User" headings/texts are now changed to "Manage User" instead

**Comment by SocanIcode** [comment]
I have updated the settings and dashboard icons and text based on your feedback. Additionally, I fixed some typographic inconsistencies, including text alignment, line spacing, and letter spacing. The updated version has now been sent for your review.

**Comment by pauiws** [comment]
It looks good, can you make sure the icons on the mobile version are of the same sizes? Otherwise, its perfect
