### ISSUE TITLE
Remove "Failed Signup" page and create error notification on Signup page

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#71]
Work together with @QueenWoofie to create an overall design for the notification ! 

## Tasks
- Remove the "Sign up Message desktop - Failed" page
- Duplicate the Sign up page next to it
- Create an alert/notification for a Failed Sign Up message
- Repeat process for mobile version

## Design
- Error: Red background (#FFEBEE), red text (#C62828), with an exclamation icon.
- Create a notification box in the top right corner under the navigation bar (or wherever looks good)
- Follow style guide for alerts

- [x] Desktop version
- [x] Mobile version

**Comment by EkremGursoy** [comment]
Im done with the task. Please give me feedback if the design is not okey. :)

**Comment by Mayamariaruth** [comment]
@EkremGursoy We are not meant to have a whole page for the Failed notification, that's why I wrote on the task to remove that page and duplicate the Sign up page which is where you will create a small notification box in the right right corner alerting the user. Like this: ![Image](https://github.com/user-attachments/assets/9e99fb51-2239-42fb-81a6-1b3fb1df0a1c)

**Comment by Mayamariaruth** [comment]
Parent ticket #86

**Comment by pauiws** [comment]
I have talked to Maya, and we agreed that we change notification design to this: 
![Image](https://github.com/user-attachments/assets/2fe6d47f-0753-4627-bd41-43468c3fba6c)

**Comment by EkremGursoy** [comment]
![Image](https://github.com/user-attachments/assets/c2ff5eae-e0b3-4454-9624-f6aded4758c4)

how about now :)

**Comment by EkremGursoy** [comment]
![Image](https://github.com/user-attachments/assets/6d4766b9-7b1b-4eef-9166-188cbb40eabc)

and mobile version

**Comment by EkremGursoy** [comment]
![Image](https://github.com/user-attachments/assets/50d32aaf-c1e7-4de8-981f-41e5705d8d27)

**Comment by Mayamariaruth** [comment]
@pauiws We will go back to the first version after discussing with the clients! Please remake it @EkremGursoy and maybe play around with the design if you find a better way to style it than we did before

**Comment by pauiws** [comment]
Review completed
