### ISSUE TITLE
Update headings and body text stylings

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#74]
### Go through every heading on every Desktop and Mobile page to align with style guide (see below):
Primary Font: Poppins (for headings and buttons) — Choose bold for headings.
Secondary Font: Roboto (for body text) — Use regular and medium weights for contrast.

Font Sizes:
Headings: H1 - 32px, H2 - 24px, H3 - 20px
Body Text: 16px for paragraphs, 14px for labels and smaller text.

Line Height: 1.5 for improved readability.
Letter Spacing: 0.5px for headings to create a crisp, clean look.

### Important!
- Update all the Headings on every page to be Bold (most of them are Black, not Bold)
- Update body font sizes on mobile (they are too small now) - should be 16px or minimum 12px at least

**Comment by BiankaSzabo** [comment]
Im done with the task, please take a look at it and give me a feedback :)
