### ISSUE TITLE
Contact form styling

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#77]
## Tasks
- Update contact form styling to match the rest of the forms on login page, signup page and registration page (update layout, form fields and labels)
- Update the other forms with placeholder and styling as written in the style guide

## Design
Border: 1px solid light gray (#CCCCCC)
Focus: Border changes to primary color (#4CAF50)
Padding: 8px
Labels: Secondary text color (#757575), small font size, and bold.
Validation Messages: Error messages in accent color (#FF5722) below the field.

**Comment by Martinekong** [comment]
I have styled the contact form with border, padding, labels and placeholders. I created a component for regular form fields and added it to all forms (contact, signup, login and registration) both on desktop and mobile. 

For the contact error form, see issue #102 that I am currently working on.

**Comment by Martinekong** [comment]
Since the background color of the site is F5F5F5, using the color 757575 for the labels fail on contrast. I have now used the color 333333 witch is a neutral color under the main colors in the style guide. I added a comment on this in the Figma file.

**Comment by Mayamariaruth** [comment]
@pauiws I added a comment to this on the Figma page !

**Comment by Martinekong** [comment]
I have now changed the contact form on desktop to vertical instead of horizontal.

**Comment by pauiws** [comment]
Great work! Review completed
