### ISSUE TITLE
User Profile Page

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#78]
As a user, I want a simple profile page layout to view and edit my information.

Acceptance Criteria:
- Sections for displaying user info (name, email) with editable placeholders.
- Buttons for actions like editing, updating or deleting the profile.
- An area for a profile picture (static placeholder).

## Tasks
- Add placeholder initials as an image for user profile pages
- Remove text "If this information is incorrect, inform your school here"
- Add buttons for actions instead (Edit Profile), (Update Profile) and (Delete Profile)
- [ ] Mobile
- [ ] Desktop

### Profile information
User Profile Card: Shows user details and profile photo.
Border: Thin line with medium gray (#757575)
Profile Picture Placeholder: Circular frame with a light gray background (#E0E0E0)

### Buttons
Secondary Button:
Outline style with secondary color border (#2196F3) and text
Hover: Light secondary color background (#BBDEFB)

Alert Button (for delete actions):
Background: Accent color (#FF5722)
Text: White
Hover: Darker shade of accent color (#E64A19)

**Comment by SocanIcode** [comment]
I believe Kristina worked on the profile field over the past two days, but I wasn’t sure if I should edit her version. To avoid any potential issues, I created a new profile field instead. I’ve now submitted it for your review. Please let me know your feedback. I’ve included all the necessary fields based on the instructions.

**Comment by Mayamariaruth** [comment]
@pauiws I added some additional Figma comments on these pages (I'm the "M" haha) with what I think but you decide

**Comment by pauiws** [comment]
I have reviewed both mobile and desktop version. I also commented on Maya's comment but i can summarise it for you. 

DESKTOP Ver.: 

- We can use Kristina's profile user we can just add the user image under profile heading
- Add an action button 
- Change the name of the "Action button" to "Edit Profile"
- Include a "back to the dasboard" like on other pages 

PROFILE ACTION DESKTOP: 

- Add the user image under profile heading 
- Delete profile button should be red "Delete" button 
- Add a "Update Profile" button but use the green color on it

MOBILE Ver.: 

- I like the first version better, add the user image under the profile heading 
- Change the name of the "Action button" to "Edit Profile"
- Include a "back to the dasboard" like on other pages 
- Delete profile button should be red "Delete" button 
-  Add a "Update Profile" button but use the green color on it

**Comment by SocanIcode** [comment]
@pauiws Could you kindly clarify your role in our group? I just want to ensure I understand everyone's contributions.

**Comment by SocanIcode** [comment]
@pauiws : Sorry, Pauiws , but I feel it’s not fair to dismiss my work as if it’s much different from Kristina’s. Constructive criticism is helpful, but it’s not about personal preferences. If there’s anything specific I need to add, like the action button for example, I’d appreciate your input. I’ve followed Maya’s task instructions, which you can review. If there's content I should include, I’m happy to do so. We’re all working on this together, and I believe I have the right to contribute as well.

**Comment by Mayamariaruth** [comment]
@SocanIcode @pauiws It was decided to keep the school information on the profile page (user ID, school name etc) and to also add labels to each information to improve accessibility and clarity (they can maybe be bold and the text be normal font weight)

Other than that, it sounds good to remove the Delete button, move the user image to below the Profile heading and also add the border (with some possible shadow to make it pop if it looks good)

**Comment by SocanIcode** [comment]
@pauiws  I have finished the padding and the style of the profile page. Please look at it and give me your feedback

**Comment by pauiws** [comment]
Looks good, Review Completed.
