### ISSUE TITLE
Create dashboard dropdown menu

### ISSUE THREAD

**Issue by Mayamariaruth** [NoroffFEU/edu-gate#79]
## Tasks
- Create Dashboard dropdown menu for Desktop when hovering over Dashboard in navigation bar
- Include "Add Teachers", "Add Students", "Edit User" pages for admin
- Include "Results", "Settings" pages for teacher
- Include "Results", "Edit User", "Settings" pages for student
- Style to match the rest of the website
- Add prototype interaction for Dashboard link in navigation bar
- Add hover/active states if applicable

**Comment by EkremGursoy** [comment]
I wonder about one thing, the dropdown menu I'm going to make, shouldn't it be on all pages
like 'Manage User' page, Change User Search page and Add Teachers page. Than we have the dropdown menu for all pages.

except

-Contact
-About
-Dashboard desktop
-Registration desktop
-Sign Up Message desktop - Success
-Sign Up Message desktop - Success
-Sign Up desktop
-Log In desktop
-Landing Page desktop

Im waiting feedback before i start with the task :)

**Comment by Mayamariaruth** [comment]
Yes, so what you will do is create one dropdown overlay for desktop and you can actually immediately prototype it to the Dashboard navigation link on one page and then you can just copy paste that navigation bar onto every page (and the prototype interaction will follow to every page) so you don't need to create one dropdown for every page. Just do one for the whole design and then add that as an interaction on every page. Hope that makes sense!

**Comment by EkremGursoy** [comment]
Hi i fnish with the dropdown menu, can you guys have a look on it and give me feedback before i copy to the other pages, i have the dropdown menu on the ''Results Students desktop''.

**Comment by Mayamariaruth** [comment]
@EkremGursoy The dropdown is supposed to be for the navbar, not as a separate dropdown on each page, see image below.
I see that the other team has created all the dashboards for the different users and they've updated the content so you can follow those pages to create a dashboard for each type of user (admin, student, teacher) and add the pages to the dropdown that you see on the different dashboard pages

[Image](https://github.com/user-attachments/assets/dd6abfae-6326-4519-a41c-fd4dd85d309d)

**Comment by Martinekong** [comment]
See issue #113 - I did some changes to the dropdown menu (font size, family and color) to make it align with the style guide - there is a problem with the contrast on hover. Maybe change the text color when hovering?

**Comment by Jereriviel** [comment]
I created three new dropdown menus from the one that Ekrem made first. I also made a few design adjustments, like changing the font and hover colors, as Martine suggested.

Admin:
- Add students
- Add teachers
- Add schools (page not created yet)
- Manage user
- Log out

Teacher:
- See results
- Add results
- See top students (page not created yet)
- Log out

Student::
- See results (page not created yet)
- Profile
- Log out

I then created two extra variants of the "Logged in Navbar", one for each overlay (Admin, Teacher and Student).

I Implemented the new Navbars and linked the menu options to their pages.

The only thing I couldn't manage to find out was how to make the overlay stay after hovering the Dashboard nav element, so I had to used Clicked. Maybe someone else can fix it, or we'll fix it in programming. :)

**Comment by kristinatonnessen** [comment]
Hey guys! just wondering now that we are looking over the sidebar, a lot of these dropdowns are supposed to be in the sidebar and not on dropdowns :) according to the styleguide they only mentioned dropdown for the profile.. 
"Structure: A sticky top bar with the logo on the left, followed by page links (Home, Results, Profile, etc.), and a profile dropdown on the right."
The requirements do say we should have a sidebar for the admin and teacher "backoffice" sites. what do we do here? keep them as they are and see if they tells us to add the sidebar after the meeting or create one now for the admin pages? @BtheBEST84

**Comment by Jereriviel** [comment]
Ah, okay, guess we misunderstood. I can change the desktop dropdown to be a profile dropdown instead? What do you think, @Mayamariaruth ?

**Comment by kristinatonnessen** [comment]
That's fine! Me and @BtheBEST84  decided to go ahead with a collapsible sidebar for both mobile and desktop with a hover effect to not disrupt the design further now with so little time left😅 they will work on that now and maybe pull some of your design into the sidebar so your work is not dismissed 💪 it looked great though 🔥

**Comment by Jereriviel** [comment]
Okay, great! :) Feel free to redesign everything, I don't mind at all. I'll remove the prototyping on the dropdown menu, just delete the old prototypes/overlays if they're in the way!

Thanks! :)
