### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by kristinatonnessen** [NoroffFEU/edu-gate#84]
Add versions of fonts and typography to the styleguide in figma

**Comment by Anne-Zwift** [comment]
@kristinatonnessen Added local variables for typography. I saw that two button sizes were already added. These formats may not match the style guide. Not sure if I should do anything with these since they might be used by someone else?

**Comment by Anne-Zwift** [comment]
Task finished.

**Comment by kristinatonnessen** [comment]
@Anne-Zwift if you could look over and see who added them by the issues and maybe ask them or see if they have open issues on that, that would be great 😃

**Comment by Anne-Zwift** [comment]
Ok I'll do that.

**Comment by Anne-Zwift** [comment]
@kristinatonnessen I assumed that the buttons would follow the description of body text but maybe I'm wrong?
Headings: H1 - 32px, H2 - 24px, H3 - 20px
Body Text: 16px for paragraphs, 14px for labels and smaller text.

**Comment by kristinatonnessen** [comment]
Check in on issue #75 and #76 and see what they think and let me know, but I would assume maybe the 16px? (Without looking on any design just the description)You could send a dm to the assignees or comment on their issue😃 ✨communication✨😉

**Comment by Janicke92** [comment]
There's been some confusion regarding the font size for buttons. I've updated the QA standards with the right font sizes.

**Comment by AilinMari** [comment]
I am reading in the styleguide that is made in Figma and it says that button size is 26px? We are not supposed to use 26px as I understand it from the guidelines we got from the "costumer"? I am trying to fix up the navbars now, but I get a bit confused by all the random numbers added all over the place. Can someone explain the thought around it? :)

**Comment by kristinatonnessen** [comment]
we have a meeting now at 19.00, i will ask Janicke and we will talk about it and get back to you!

**Comment by Janicke92** [comment]
Looks great! Only need changes for the font size for buttons

**Comment by Anne-Zwift** [comment]
@Janicke92 I have changed the button sizes to 26 px according to the style guide.

**Comment by Janicke92** [comment]
Great!
