### ISSUE TITLE
Forms (Input fields)

### ISSUE THREAD

**Issue by Tomatsuppe11211** [NoroffFEU/edu-gate#85]
- [x] Styling
       - Border: 1px solid light gray (#CCCCCC)
       - Padding: 8px
       - Labels: Secondary text color (#757575), small font size, and bold.

<br>
<br>

- [x] Focus
       - Border changes to primary color (#4CAF50)

<br>
<br>

- [x] Validation message
       - Error messages in accent color (#FF5722) below the field.

- #77

**Comment by Mayamariaruth** [comment]
@Martinekong has completed the contact form field styling on issue #77 and created components for the form field

**Comment by Martinekong** [comment]
I completed issue #77 and had some time to check the rest of the form fields, I hadnt seen this task so hope that was ok!

**Comment by Foadosman** [comment]
I duplicated the login page and changed the border-color to primary color to see how the input field looks in focus.

**Comment by Janicke92** [comment]
A group decision was made to temporarily change the color of "Labels" from #757575 to #333333 because of contrast with the background. 

It looks great! It follows the requirements from the Style guide.
