### ISSUE TITLE
Alerts and notifications

### ISSUE THREAD

**Issue by Tomatsuppe11211** [NoroffFEU/edu-gate#86]
As a user, I want to receive clear alerts or notifications, so that I can stay informed about important actions or updates in the application.

## Acceptance criteria
- Alerts are displayed prominently when action has been implemented.
- Notifications are accessible via a dedicated section or dropdown.
- Alerts and notifications include a clear title and concise message.
- Alerts should include a success message and error message.

## Design
- Sucess
       - Green background (#E8F5E9), green text (#388E3C), with a check icon.

- Error
       - Red background (#FFEBEE), red text (#C62828), with an exclamation icon.

- Warning
       - Yellow background (#FFF3E0), yellow text (#FFA000), with a warning icon.

<br>

- [x] #71 
- [x] #101

**Comment by Mayamariaruth** [comment]
Willow Glade is completing the Sign up error notification on issue #71

**Comment by pauiws** [comment]
Unsure of the design, still reviewing it and maybe will come with better design :)

**Comment by pauiws** [comment]
I have talked to Maya, and we agreed that we change notification design to this: 
- The success message can be changed to the primary color green 
![Image](https://github.com/user-attachments/assets/2fe6d47f-0753-4627-bd41-43468c3fba6c)

**Comment by pauiws** [comment]
The mobile version is good, but the mobile version is not of the same size.

**Comment by pauiws** [comment]
Review completed.
