### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by Tomatsuppe11211** [NoroffFEU/edu-gate#88]
As a user/admin/teacher, I want to view information in a table format, so that I can easily scan, compare, and understand the data.

## Acceptance criteria
- Display data in a structured table with headers.
- Ensure table is responsive and readable on all screen sizes.
- Highlight rows or cells on hover for better readability.
- Include Edit and Delete buttons (for admin) to easily update table information

## Design
- headers
        - Use primary color text and bold font for clarity.

- Rows 
       - Alternate light gray background (#F9F9F9) to improve readability.

- hover
       - Slight background change on row hover to indicate interactivity.
      
<br>

- [x] #63 
- [x] #105

**Comment by Mayamariaruth** [comment]
Willow Glade is already completing the tables on this issue #63

**Comment by Jereriviel** [comment]
#63 Pagination and table styling in review.

**Comment by Jereriviel** [comment]
https://github.com/NoroffFEU/edu-gate/issues/105 Add hover/click states to tables in review.

**Comment by pauiws** [comment]
Review completed
