### ISSUE TITLE
Lo-Fi Wireframes and user flow

### ISSUE THREAD

**Issue by kristinatonnessen** [NoroffFEU/edu-gate#91]
Create an lo-fi wireframe of the different pages, and create a user flow guide 

Should include :
- every mentioned page, you can make different groupings for student, teatcher and admin or use general terms
- arrows or guides during the user flow

Jørn-andre will continue on this task, janicke´s contribute can be found in the figma file under style guide

**Comment by barumski** [comment]
Ready for review

**Comment by Janicke92** [comment]
Looks great! :)
